app = "tgbot-lbqj1g"

[env]
PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

  [services.concurrency]
    hard_limit = 20
    soft_limit = 15
    type = "requests"